trigger:
  - master

jobs:
  - job: lint
    pool:
      vmImage: "macOS-10.15"
    steps:
      - bash: ./lint.sh

  - job: test
    pool:
      vmImage: "macOS-10.15"
    steps:
      - bash: ./test.sh
      - bash: ./codecov.sh
        env:
          CODECOV_TOKEN: $(codecovToken)
        condition: succeeded()
