name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@master
        with:
          shell-action: swift build --triple wasm32-unknown-wasi --product TokamakDemo

  macos_build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on macOS, build the demo project for iOS
        shell: bash
        run: |
          set -ex
          sudo xcode-select --switch /Applications/Xcode_12_beta.app/Contents/Developer/
          swift test
          xcodebuild -version
          cd "NativeDemo"
          xcodebuild -scheme iOS -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | \
            xcpretty --color
