
name: Codecov

on:
  pull_request:
  push:
    branches: [main]

jobs:
  codecov:
    container:
      image: swift:5.3.2-bionic
    runs-on: ubuntu-latest
    steps:
    - run: apt-get update && apt-get install -y gtk+-3.0 libgtk+-3.0
    - uses: actions/checkout@v2
    - run: swift build --enable-test-discovery -Xswiftc -profile-coverage-mapping -Xswiftc -profile-generate --product TokamakPackageTests
    - run: swift test --enable-test-discovery --enable-code-coverage --skip-build
    - name: Coverage Report
      uses: mattpolzin/swift-codecov-action@0.6.0
      id: cov
      with:
        MINIMUM_COVERAGE: 98
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc
      with:
        body-includes: The current coverage percentage is 
    - name: Create comment
      if: ${{ steps.fc.outputs.comment-id == 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The current code coverage percentage is ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.output.minimum_coverage }}%).
    - name: Update comment
      if: ${{ steps.fc.outputs.comment-id != 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with: 
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          The current code coverage percentage is ${{ steps.cov.outputs.codecov }} (minimum allowed: ${{ steps.cov.output.minimum_coverage }}%).

