
name: Codecov

on:
  pull_request:
  push:
    branches: [main]

jobs:
  codecov:
    container:
      image: swift:5.3.2-bionic
    runs-on: ubuntu-latest
    steps:
    - run: apt-get update && apt-get install -y gtk+-3.0 libgtk+-3.0
    - uses: actions/checkout@v2
    - run: swift build --enable-test-discovery -Xswiftc -profile-coverage-mapping -Xswiftc -profile-generate --product TokamakPackageTests
    - run: swift test --enable-test-discovery --enable-code-coverage --skip-build
    - uses: mattpolzin/swift-codecov-action@0.6.0
      with:
        MINIMUM_COVERAGE: 98
    - name: comment PR
      if: ${{ always() }}
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      with:
        msg: "Your current code coverage percentage is ${{ env.CODECOV }} (minimum allowed: ${{ env.MINIMUM_COVERAGE }})."
        check_for_duplicate_msg: false
