# This is a basic workflow to help you get started with Actions

name: Danger

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  danger-lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Danger Swift
        uses: maxdesiatov/danger-swift@swiftlint-docker
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.PAT }}
